apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ottero-ingress
  namespace: ottero
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  tls:
    - hosts:
        - ottero.com.au
      secretName: ottero-tls
  rules:
    - host: ottero.com.au
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ottero-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ottero-frontend
                port:
                  number: 80
