apiVersion: v1
kind: Namespace
metadata:
  name: ottero
---
apiVersion: v1
kind: Service
metadata:
  name: ottero-frontend
  namespace: ottero
spec:
  selector:
    app: ottero-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ottero-backend
  namespace: ottero
spec:
  selector:
    app: ottero-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
